name: automata
favicon: null
layout_spectrum: 0.74138
typography_spectrum: 0.74138
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#e9e9e9'
    - '#bdbcbc'
    - '#a4a3a3'
    - '#989393'
    - '#7a7373'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.3125
  rhythmicContrast: 1
purpose: []
