typography_spectrum: 0.74138
color:
  brandColors:
    - '#e9e9e9'
    - '#bdbcbc'
    - '#a4a3a3'
    - '#989393'
    - '#7a7373'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
github: true
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.269589
analytics:
  google: null
  facebook: null
  twitter: null
name: automata
cta:
  domain: null
  bucket: null
  version: null
navigation:
  - name: About
    id: 4a7fb400-62eb-4b77-b89b-82f044b4f523
    type: content
  - name: Drawings
    id: 5c33d3ce-282a-4f66-a376-e7934cf00f7f
    type: content
favicon: null
title: Vilson Vieira
content: []
description: ''
purpose: []
