analytics: {}
color:
  brandColors:
    - '#e9e9e9'
    - '#bdbcbc'
    - '#a4a3a3'
    - '#989393'
    - '#7a7373'
  brandStrength: 0.9375
  lightness: 1
  rhythmicContrast: 1
  saturation: 0.3125
cta: {}
layout_spectrum: 0.269589
name: automata
opengraph: {}
purpose: []
typography_spectrum: 0.74138
