typography_spectrum: 0.74138
color:
  brandColors:
    - '#e9e9e9'
    - '#bdbcbc'
    - '#a4a3a3'
    - '#989393'
    - '#7a7373'
  brandStrength: 0.9375
  lightness: 1
  saturation: 0.25
  rhythmicContrast: 0.75
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.269589
analytics:
  google: null
  facebook: null
  twitter: null
name: automata
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: Vilson Vieira
description: I create algorithms that create
purpose: []
